try {
    console.log('Normal');
    // console.log(a);
    console.log('resurls');
} catch (error) {
    console.log(error.name);
}

console.log('Still normal');